### ISSUE TITLE
[REQUEST] New Server Listing: Gaia XI

### ISSUE THREAD

**Issue by evenmonkeys** [XiPrivateServers/Servers#18]
**Server Name**
Gaia XI

**Server Website/Links**
https://gaiaxi.com
https://discord.gg/2c6HjwNuNK

**Server Level Cap**
75

**Server Content Type**
Enough modified to be custom

**Server Expansion**
Treasures of Aht Urhgan

**Server Rates**
EXP x5, Skillups x2, HP x2, MP x1.5, Drop Rates Increased, etc

**Server Move Speed**
x2

**Level Sync?**
Yes

**Trusts?**
No

**Dual-Boxing?**
2 accounts online per player at a time

**Additional Information**
https://gaiaxi.com/server.xi

**Comment by atom0s** [comment]
Added / approved. ✔️
