### ISSUE TITLE
[REQUEST] China 99 Server

### ISSUE THREAD

**Issue by zanglikun** [XiPrivateServers/Servers#23]
**Note:** Before submitting your server to be added to the main list, please be sure you meet the expected requirements listed in our **[Guidlines](https://github.com/XiPrivateServers/Servers/blob/main/GUIDELINES.md)**!

---

**Server Name**

Origin

**Server Website/Links**

http://update.ff11sf.com

**Server Level Cap**

99/49

**Server Content Type**

custom

**Server Expansion**

ALL MAPS

**Server Rates**

all set 1.0

**Server Move Speed**

default

**Level Sync?**

yes

**Trusts?**

yes

**Dual-Boxing?**

yes

**Additional Information**

**Comment by atom0s** [comment]
Added. :)
