### ISSUE TITLE
[REQUEST] CANCEL

### ISSUE THREAD

**Issue by AlexandreCA** [XiPrivateServers/Servers#26]
**Note:** Before submitting your server to be added to the main list, please be sure you meet the expected requirements listed in our **[Guidlines](https://github.com/XiPrivateServers/Servers/blob/main/GUIDELINES.md)**!

---

**Server Name**

_Please enter your servers name here._
Vanadiel XI
**Server Website/Links**

_Please link us to your servers website, wiki, etc._
https://discord.gg/Kkb447eGzm
**Server Level Cap**

_What is the level cap of your server?_
99
**Server Content Type**

_Is your server retail-like or custom?_
retail-like
**Server Expansion**

_What expansion does your server support upto?_
The content developed by LSB works.
**Server Rates**

_What kind of rates does your server have? (Exp, skillups, etc.)_
retail-like
**Server Move Speed**

_What is the movement speed on your server?_
retail-like
**Level Sync?**

_Is Level Sync enabled on your server?_
Yes.
**Trusts?**

_Are Trusts enabled on your server?_
Yes.
**Dual-Boxing?**

_Are players allowed to dualbox on your server? If so, what kind of limits/rules do you have?_
No.
**Additional Information**

_If you would like to share more information about your server, fill it in here._
We have our own client. Available for download on our discord.

**Comment by atom0s** [comment]
Closing as this has been renamed to 'CANCEL'. Assuming the application has been revoked.
If you wish to apply again in the future, please do. :)
