### ISSUE TITLE
[REQUEST] Level Down 99 Custom and Level Down 75 Custom

### ISSUE THREAD

**Issue by FFXILevelDown** [XiPrivateServers/Servers#28]
**Note:** Before submitting your server to be added to the main list, please be sure you meet the expected requirements listed in our **[Guidlines](https://github.com/XiPrivateServers/Servers/blob/main/GUIDELINES.md)**!

---

**Server Name**
_Please enter your servers name here._
Level Down 99
Level Down 75

**Server Website/Links**
_Please link us to your servers website, wiki, etc._
https://ffxileveldown.fandom.com/wiki/FFXILevelDown_Wiki
https://discord.gg/qcQBh46j
https://www.facebook.com/groups/1622567248533657/

**Server Level Cap**
_What is the level cap of your server?_
99/99
75/37

**Server Content Type**
_Is your server retail-like or custom?_
Custom

**Server Expansion**
_What expansion does your server support upto?_
Level Down 99 - All expansions
Level Down 75 - Up to Wings of the Goddess

**Server Rates**
_What kind of rates does your server have? (Exp, skillups, etc.)_
Exp rate - retail - !buff command active to 500%
Skill up rates - Automatically skill up to max on level up
Craft Rate Skill up - 99.9%
Subjob levels with main job with restrictions

**Server Move Speed**
_What is the movement speed on your server?_
50

**Level Sync?**
_Is Level Sync enabled on your server?_
Yes

**Trusts?**
_Are Trusts enabled on your server?_
Yes

**Dual-Boxing?**
_Are players allowed to dualbox on your server? If so, what kind of limits/rules do you have?_
Dual Boxing allowed - two active, one mule

**Additional Information**
_If you would like to share more information about your server, fill it in here._
1 year in the making, We started this journey as Level Down 99, a group of friends who were looking for a place to enjoy the game and not feel as if it was a second job. Somewhere along the lines our name was passed from person to person and eventually we took on an additional private server who was struggling. Now rebranded to Level Down 75. Our goal is to offer players a fun place to spend time, play at your own pace and have as much interaction with the community, staff and other players as possible. 

Not sure I should submit two New Server Listing Requests as this is two servers, hosted in two different locations.

**Comment by atom0s** [comment]
Hello and welcome. Your server has been approved and added to the list.

Default pages have been added for your servers, which you can now edit by forking this repo and making changes/updates to them. The current default pages can be found here:

  - 75cap: https://github.com/XiPrivateServers/Servers/blob/main/servers/75_custom/leveldown.md
  - 99cap: https://github.com/XiPrivateServers/Servers/blob/main/servers/99_custom/leveldown.md
