### ISSUE TITLE
[REQUEST] Cactuar Server Listing Request

### ISSUE THREAD

**Issue by CynicaGaming** [XiPrivateServers/Servers#6]
[cactuar.md](https://github.com/XiPrivateServers/Servers/files/10413140/cactuar.md)
**Note:** Before submitting your server to be added to the main list, please be sure you meet the expected requirements listed in our **[Guidlines](https://github.com/XiPrivateServers/Servers/blob/main/GUIDELINES.md)**!

---

**Server Name**

Cactuar

**Server Website/Links**

https://www.discord.gg/DP59SmXN7v
Server website is under construction and coming soon.

**Server Level Cap**

75

**Server Content Type**

Custom

**Server Expansion**

Wings of the Goddess

**Server Rates**

2x EXP
2x Crafting

**Server Move Speed**

+12% Players
+12% Mobs

**Level Sync?**

Yes

**Trusts?**

No

**Dual-Boxing?**

No

**Additional Information**

We have a dual main job system. Essentially you are able to use the abilities, merits, gear, etc. of your support job. You are also able have multiple rare items in your inventory and equip multiple rare armor and weapons.

**Comment by atom0s** [comment]
Added to the server list. 👍
